apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zp1cbsxxu-nodejs 
  janus-idp.io/tekton: zp1cbsxxu-nodejs
  backstage.io/kubernetes-id: zp1cbsxxu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zp1cbsxxu-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml