apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zp1cbsxxu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zp1cbsxxu-nodejs 
  name: zp1cbsxxu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zp1cbsxxu-nodejs 
